[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./sys/docker/Dockerfile.armv7-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./sys/docker/Dockerfile.aarch64-unknown-linux-gnu"
